name: pause72
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.5
  google_sign_in: ^6.2.2

  # Routing
  go_router: ^14.8.1

  # Local Storage
  shared_preferences: ^2.3.3

  # Ads
  google_mobile_ads: ^5.3.0

  # Social Login
  # kakao_flutter_sdk_user: ^1.9.0

  # Local Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.0

  # Network
  http: ^1.2.2

  # Image
  image_picker: ^1.1.2
  path_provider: ^2.1.5

  # Utilities
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  kakao_flutter_sdk_user: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.5
  freezed: ^3.0.0
  json_serializable: ^6.9.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/app_icon.png'
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: false
