// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwILMz-OMHuOZn8b1H8li6wJRNp-Q1wp8',
    appId: '1:304393749591:web:b58498d10c24b128548f12',
    messagingSenderId: '304393749591',
    projectId: 'pause72-31936',
    authDomain: 'pause72-31936.firebaseapp.com',
    storageBucket: 'pause72-31936.firebasestorage.app',
    measurementId: 'G-94RNBMY085',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdUU7wnXXbkNXy7Z9Z55Mh0iuIPyURiYU',
    appId: '1:304393749591:android:5302f6e090cdd33a548f12',
    messagingSenderId: '304393749591',
    projectId: 'pause72-31936',
    storageBucket: 'pause72-31936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNlysx8rYfyf1AKPhOUu44Wo1-R3uD6Rk',
    appId: '1:304393749591:ios:eb8594df8b520657548f12',
    messagingSenderId: '304393749591',
    projectId: 'pause72-31936',
    storageBucket: 'pause72-31936.firebasestorage.app',
    iosBundleId: 'com.pause72.pause72',
  );
}
