// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaA8pu6QwK_9RoILDdhtXi25PmAE_7Uvk',
    appId: '1:884745183528:web:58e772e62b1466560bf01d',
    messagingSenderId: '884745183528',
    projectId: 'jireummak',
    authDomain: 'jireummak.firebaseapp.com',
    storageBucket: 'jireummak.firebasestorage.app',
    measurementId: 'G-L9TN9DBPBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACDipjfFnEv8chvkrCh7xhJzkBpNUuWIk',
    appId: '1:884745183528:android:2a5296df5cf347b70bf01d',
    messagingSenderId: '884745183528',
    projectId: 'jireummak',
    storageBucket: 'jireummak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtt3QEezbJeTvOaiKK36bSixk3YesS5pQ',
    appId: '1:884745183528:ios:2c6cb415560075ed0bf01d',
    messagingSenderId: '884745183528',
    projectId: 'jireummak',
    storageBucket: 'jireummak.firebasestorage.app',
    iosBundleId: 'com.pause72.jireummak',
  );

}